### ISSUE TITLE
Control buttons in output control section of ultrasync

### ISSUE THREAD

**Issue by jxmagnus** [caronc/ha-ultrasync#13]
Hi

Thank you for the amazing work on this. It just added a whole extra level to my alarm system.

I had a button set in the output control section of the Ultrasync app which was wired to control my garage door. I was wondering if there was any way i could turn it on or off using this with home assistant.

**Comment by caronc** [comment]
Possibly, can you toggle the button through your home assistant control panel?

Basically anything that can be controlled via the Ultrasync web page (not to be confused with the panel options you can touch/interact with physically) can be controlled.

**Comment by caronc** [comment]
You never got back; i was just curious; does your alarm panel allow you to close your garage door (through it's web page)? Were you able to try/test this at all?

**Comment by jxmagnus** [comment]
Hi really sorry for the delay in getting back to you. I just tried logging into the Web interface and yes it does 
![Screenshot_20210930-143726_Edge](https://user-images.githubusercontent.com/77110273/135388298-46489305-d1c9-49e6-8a79-1df3477658e0.jpg)
Under menu> output control there is an option for garage door on and off. To open the door I have to press on then off straight away.

**Comment by GeorgeCastanza** [comment]
This would be cool, if this could be integrated.  I have the same thing.  I have my garage door hooked up to the first output, and nohting to the second. I open my garage door using other means too (but I'm having issues with the other means), and am hopeful for this.

**Comment by GeorgeCastanza** [comment]
How would I do this? I just looked in my Ultrasync directory, and I cant find the second Ultrasync subdirectory??
![image](https://user-images.githubusercontent.com/30585632/150449498-994a9c35-1dd9-45d6-bfcd-4ae732baeb11.png)

**Comment by caronc** [comment]
The first thing to do is just create a text file.  You can use `notepad.exe` if you're in Windows, or any editor of your choice in Linux/Mac.  The text file just has to have 3 entries in it; this will be your config file to use this script.  It's the same things you need to provide Home Assistant in order for it to work there too:
```yaml
# the ip to your ComNav Security Panel
host: 192.168.0.30
# The Web User ID you use to log into it with:
user: My Username
# Your Pin:
pin: 1234
```

Check out a copy of [ultrasync](https://github.com/caronc/ultrasync) if you can't access it from your Raspberry Pi (where Home Assistant is) as it will be already available to you there.   You'll need to do a  `--debug-dump` for me:
1. Use your Home Assistant Pi instance if you can:
    ```bash
    # Call the ultrasync tool referencing your configuration file you created
    # along with --debug-dump
    bin/ultrasync -c /path/to/config --debug-dump
   ```
1. Use **git**:
    ```bash
    # Clone the repository:
    git clone https://github.com/caronc/ultrasync.git

    # Change to the directory you just cloned to (with respect to the above, you'd
    # have created an ultrasync directory):
    cd ultrasync

    # Now call the ultrasync tool referencing your configuration file you created
    # along with --debug-dump
    bin/ultrasync -c /path/to/config --debug-dump
    ```
1. Use `pip` if you already have Python (v3) installed on your pc:
    ```bash
    # Install ultrasync:
    pip install ultrasync

    # Now call the ultrasync tool referencing your configuration file you created
    # along with --debug-dump
    ultrasync -c /path/to/config --debug-dump
    ```
1. Just [download a the zip file of this current branch with your browser](https://github.com/caronc/ultrasync/archive/master.zip), unzip it and then from a command line:
    ```bash
    # Change to the directory you just unzipped your content to:
    cd ultrasync

    # Now call the ultrasync tool referencing your configuration file you created
    # along with --debug-dump
    bin/ultrasync -c /path/to/config --debug-dump
    ```

This will produce a zip file you can pass back to me with slightly more files then the ones you already shared. It will allow me to see your panel information (so i can recreate your crash and fix it).

Also, all UltraSync devices only allow 1 login per user at a time.  So create a separate account for your Home Assistant user (and these tests).  Also, if your Home Assistant configuration is still set up,  remove it (otherwise Home Assistant will be competing with your testing as it will continuously try to log in over and over again) while you help me out here :slightly_smiling_face: .  Hopefully this all makes sense!

Please let me know if you have any questions or concerns or are having any issues with the info above.

**Comment by Ay1tsMe** [comment]
+1 this feature request. I am also in the same boat. I am using the hills comnav and I have an output control linked up to my garage door and it would be so handy if I was able to control the garage door through home assistant. 

I also did a debug-dump like you asked. This is the result when i used `grep` on everything in the zip:
```
❯ grep -r "output"
lang_engau.js:var outputLanguage = new Array(
status.js:function buildOutput(output)
status.js:  div1.id = ("o" + output);
status.js:  div1.getElementsByTagName('h1')[0].innerHTML = outputLanguage[2] + ' ' + output;
master.js:    <li><a onclick="document.getElementById(\'newpage\').setAttribute(\'action\',\'/user/outputs.htm\');document.getElementById(\'newpage\').submit(); ">'+menuNames[3]+'</a></li>';
master.js:// 2  /user/outputs.htm       ~ma(4)~
master.js:    document.getElementById('newpage').setAttribute('action', '/user/outputs.htm');
```

Like @Rhomax stated above, it looks like the `master.js` file references a outputs.htm file but there is no file of that name in the debug-dump. Below is my debug-dump.zip:

[20230712115400.ultrasync-dump.zip](https://github.com/caronc/ha-ultrasync/files/12023623/20230712115400.ultrasync-dump.zip)

I'm happy to work on getting this feature within home assistant and help you with any sort of debugging requests as like you said, you're implementing this feature blind.

Well done on all the progress so far :+1:

**Comment by Ay1tsMe** [comment]
Just a follow up to my previous reply. This is what the `outputs.htm` file looks like through the web interface:
https://picoshare.tuxtower.net/-CbK4QpJuvW

Not sure if this is any help but hopefully it gives you an idea on what needs to done to integrate the outputs.htm with the current build.

**Comment by Ay1tsMe** [comment]
I forked the git [here](https://github.com/Ay1tsMe/ultrasync) and did some testing and was able throw together an output_control function that can get all the "output controls" on the alarm system and print them to terminal. I also was able to make a request to the output.cgi with the payload which successfully opens my garage door.

However, what I have written does not fully work as I'm unfamiliar with the project so I'm still understanding. It hasn't been implemented with the cli properly in the way you have done for all the zones and areas. The way I've been testing is my writing:
```
ultrasync -c config.txt -d
```
which obviously is NOT the way to be debugging this properly. I think I've figured out the hardest part of being able to switch on and off the outputs. It's just a matter of rewriting my code so it can work properly with the cli and integrating it within this home assistant wrapper. 

Hopefully this helps with implementing this feature.

**Comment by Ay1tsMe** [comment]
For those waiting for output control support, it is finally on the main branch: https://github.com/caronc/ha-ultrasync/commit/3428d1c6a26b04106da8601d9bc799b41fd55bc6

Re-downloading and selecting the main version with HACS will give you access to your output control panel in home assistant. 

Documentation on how to operate your outputs is [here:](https://github.com/caronc/ha-ultrasync#services)

(This issue is good to close now 😊)

**Comment by caronc** [comment]
I'll bump the version this weekend if i can
