### ISSUE TITLE
Unsupported Vendor XG

### ISSUE THREAD

**Issue by 33Fraise33** [caronc/ha-ultrasync#3]
Hello,

I'm trying to add my alarm system through the HACS integration but I'm getting the following issue:

```
Logger: ultrasync
Source: /usr/local/lib/python3.8/site-packages/ultrasync/main.py:184
First occurred: 10:21:33 (1 occurrences)
Last logged: 10:21:33

Unsupported vendor XG
```

My model is the: NXG64IP
With firmware version: A56P002005-18

Is this platform not supported or am I doing something wrong?

**Comment by caronc** [comment]
It turns out there are lots of Ultrasync models out there 😯. I've added 2 models now, I was not aware of yours until now.

In order to add you system too, I will need your help (as you're the only one who can test it). I hope that's okay?

To start off, I'll need you to log into the web based page of your alarm panel and save the html file for me to disk. I will probably need a few more things, but the main login page will be a fantastic start. The HTML code is what this tool scraps. I need to see what yours looks like and see how it differs from the other models.

Just to clarify, I want the HTML code, not a picture/screenshot 🙂

If you're uncomfortable posting the contents publicly here, just send it to my email at lead2gold@gmail.com.

**Comment by 33Fraise33** [comment]
Hello,

here are login.html (screen before I log in) and index.html (main page).

If you need any more info, please let me know. 
[html-files.zip](https://github.com/caronc/ha-ultrasync/files/5728504/html-files.zip)

**Comment by caronc** [comment]
@33Fraise33 I finally merged all of our changes into this Home Assistant main branch. Your xGen support should be good to go! :+1:

**Comment by 33Fraise33** [comment]
Thanks I'll give it a try ! I should be able to pull it through hacs now?

**Comment by caronc** [comment]
Yup! Pull in the latest updates and give it a go! Let me know how it goes :+1:
